trigger:
- main

pool:
  name: 'Default'
  demands:
  - agent.name -equals myagent01



steps:
- script: sudo docker build -t akzajohn/kubehello:v5 .
  displayName: 'Build Docker Image...'


- script: 
    pwd;
    sudo docker login -u ajacr001 --password "IuZF/+jnjj2/GAv9IKNih1HkMIMDZ/0WuHpNeEexlW+ACRBw4VQK" ajacr001.azurecr.io;
  displayName: 'Docker Login..'
