trigger:
- main

pool:
  name: 'Default'
  demands:
  - agent.name -equals myagent01


steps:
- script: sudo docker build -t kubehello:$(Build.BuildId) .
  displayName: 'Build Docker Image...'


- script: 
    pwd;
    sudo docker login -u ajacr001 --password "IuZF/+jnjj2/GAv9IKNih1HkMIMDZ/0WuHpNeEexlW+ACRBw4VQK"  ajacr001.azurecr.io;
  displayName: 'Docker Login..'

 

- script: sudo docker tag kubehello:$(Build.BuildId) ajacr001.azurecr.io/kubehello:$(Build.BuildId);
  displayName: 'Tag Docker Image'